### PR TITLE
HTML/CSS Newsweek Bootstrap

### PR DESCRIPTION
**Pull request by digitekh2i**
For the purpose of educational practical exhibition for learning bootstrap, i recreated newsweek homepage, with most of the styling and responsive build buildup attributed to bootsrap as part the Microverse Technical Curriculum Assignment.

### CODE REVIEW

**Review by kevcap — CHANGES_REQUESTED** [review]
# [STATUS] CHANGES REQUIRED♻️

#### Hey @digitekh2i , for a first review, your project looks really nice! I can see that you are working hard on it, and don't worry, we're almost done, there are just some required changes that you have to implement, so you can keep going with that amazing work!

_Note_: That changes marked as [OPTIONAL] are not required to approve your project, but I strongly recommend that you guys go for that extra mile, in order to get more knowledge and have a better project to add at your portfolio.

## [REQUIRED CHANGES]
#### Clone REQUIREMENTS 👥 (Those adjusts to make your page really look like the real one)⤵
- [ ] Kindly make some improvements in the layout (In desktop screens it's looking good, but in medium and small screens, the layout isn't matching)
- [ ] Add navbar to medium and small screens
- [ ] Your page have some overlappings, please fix them (I've made some drawings to make it easier to visualize);

#### Good practices REQUIREMENTS (Those changes to make you code like a pro 👽)⤵
- [ ] Check usage of [semantic HTML](https://www.w3schools.com/html/html5_semantic_elements.asp)  (e.g. ) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/semantic_html_requirement.png) from Pathwright) (Whenever possible replace `<div>` tags for `<section>` tags.)
- [ ] Kindly remove all the commented code 👀
image


### The main goal of this project is to make that clone page responsive, and in order to achieve that:
- [ ] Your columns and layout of all three viewports (small, medium and large) should be equal to the original one, you page is facing some overlapping and other issues. Check the drawings below:
<table>
 <tr>
 <th>Yours</th>
 <th>Original</th>
 </tr>
 <tr>
 <th>Large (1024px)</th>
 <th>Large (1024px)</th>
 </tr>
 <tr>
 <td></td>
 <td></td>
 </tr>
 <tr>
 <th>Medium (768px)</th>
 <th>Medium (768px)</th>
 </tr>
 <tr>
 <td></td>
 <td></td>
 </tr>
<th>Small (375px)</th>
 <th>Small (375px)</th>
 </tr>
 <tr>
 <td></td>
 <td></td>
 </tr>
</table>


## Summary
✨ Nice usage of the bootstrap!
✨ You have a good understanding of semantic HTML, however, remember to always replace `<div>` tags for something more semantic. 
✨ Awesome CSS practices, congrats 😎
🔧 Please make the required changes and keep up the good work! 👨‍💻


## Please make the required changes and resubmit for a new code review once you are ready💪

## As always, I wish you the very best and see you at the top🚀

👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question about this review? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> gmail</a> [Twitter Follow](https://twitter.com/intent/follow?screen_name=kevinnnmn) [](https://microverse-students.slack.com/team/UT86D3AP4)

**Comment by digitekh2i** [comment]
Thank you kevin.
i have made all the corrections you pointed out.

**Review by MuriloRoque — CHANGES_REQUESTED** [review]
# Status: Changes requested :red_circle: 

## Hello @digitekh2i :wave: 

## Thank you for making most of the required changes from the last TSE, you are doing a great job. But we still need to fix somethings:

- [ ] Please change your < div > tags for < section > tags where it's appropriate, like the previous TSE recommended. You currently have no < section > tags, and they are important for maintaining your HTML semantic.

- [ ] In size 768px, check the section after Editor's Pick, your columns to the right shouldn't be squeezed like they are:

Screenshot from 2020-08-25 13-34-19

- [ ] On small screens, your first section should be 'Top Stories', currently it's 'In the Magazine', please follow the original page order. Also, please try adding a margin to the top, it's too close to the navbar:

Screenshot from 2020-08-25 13-37-50

- [ ] Don't forget to update your Live Link in your README file, it's not reflecting the changes you did in the last review.

# Summary

- Your project is amazing, you have a very nice understanding of the HTML, Bootstrap and CSS, congratulations :clap: 
- We just have to fix these issues I pointed out to move on, alright?

## Kindly make the requested changes and submit for another review, please :pray: 

## I will be on Slack 24/7 in case you have any questions about this review :handshake: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[Twitter Follow](https://twitter.com/MuriloRoquePai1)

**Comment by digitekh2i** [comment]
Hi Murilo
Thank you for your feedback.
I have made all the necessary changes.

**Review by MuriloRoque — CHANGES_REQUESTED** [review]
# Status: Changes requested :red_circle: 

## Hello again @digitekh2i :wave: 

## Thank you for making the changes, but unfortunately, I think you generated a bug in the large screen :grimacing: look below:

Screenshot from 2020-08-25 17-23-42

- [ ] I can't see your third column, I believe it went down the page, can you please fix it?

## Kindly make the requested changes and submit for another review, please :pray: 

## I will be on Slack 24/7 in case you have any questions about this review :handshake: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[Twitter Follow](https://twitter.com/MuriloRoquePai1)

**Comment by digitekh2i** [comment]
Hi Murilo,
after several hours... I managed to fix the bug.
it was as a result of trying to change some divs to section.
if it's just about divs and sections, i'd like to move on from this phase, as I have endeavored to make all the necessary required changes.

Thanks for your feedback

**Review by tirthajyoti-ghosh — CHANGES_REQUESTED** [review]
# Changes required 🛑 

## Impressive progress so far 💪! Thanks for making all the changes 👏.

### However, we need to work on some small changes before we can merge.

- The navbar - `U.S World Business Tech & Science....` is overflowing is larger screens. Please fix this.

   image

- Please remove the `!important` from your CSS rule. Use selectors with higher specificity to override styles.

  image


Your project looks absolutely fantastic. Just make these changes and apply for another code review.

Happy coding 👨‍💻 

*Need help? Shoot me a message on Slack - [@Ghosh](https://app.slack.com/client/T47CT8XPG/DRDM6LAQN/user_profile/URB1MHXK6)*
<hr>

**Tirthajyoti Ghosh**

[GitHub](https://github.com/tirthajyoti-ghosh) | [LinkedIn](https://www.linkedin.com/in/tirthajyoti-ghosh/) | [Twitter](https://twitter.com/terrific_ghosh)

**Comment by digitekh2i** [comment]
Hi Tirthajyoti,
i have made all the corrections you pointed out.
thank you

**Review by MuriloRoque — APPROVED** [review]
# Status: Approved :green_circle: 

## Hello again @digitekh2i :wave: 

## Thank you for making all of the required changes, your project is approved :clap: :clap: :clap: 

## You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[Twitter Follow](https://twitter.com/MuriloRoquePai1)

**Comment by digitekh2i** [comment]
Noted!

Thank you, Murilo.

**Pull request merged**
